### ISSUE TITLE
hp bar with a gap

### ISSUE THREAD

**Issue by Fropxy** [XiconQoo/Gladdy#1]
Hi.
I installed this addon on classic tbc and got a few issues with hp and mana bar. Mana bar pull was completely  invisible as if was 0, but actually i was full mana, Hp bar now with a gap, u can see this on warriors hp on scrennshot. I have deleted an addon but issue with hp bar was not solved.
https://ibb.co/kBtqqsF

upd.
i disablel all addons an it looks like it has being fixed after this. 
now i am playing with all my addons.

**Comment by XiconQoo** [comment]
alright. So it seems a conflict with another addon.
